salones:
    resource: "@SalonesBundle/Resources/config/routing.yml"
    prefix:   /

enfermeria:
    resource: "@EnfermeriaBundle/Resources/config/routing.yml"
    prefix:   /

activos:
    resource: "@ActivosBundle/Resources/config/routing.yml"
    prefix:   /

deportes:
    resource: "@DeportesBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

ud_enfermeria_reporte_search:
    path: /ud/enfermeria/reporte/search/{id}
    defaults: { _controller: "EnfermeriaBundle:ReporteEmergencia:search"}
    options:
            expose: true

ud_deportes_prestamo_cantidad:
    path: /ud/deportes/prestamo/cantidad/{id}
    defaults: { _controller: "DeportesBundle:PrestamoDeportes:cantidad"}
    options:
            expose: true

ud_deportes_prestamo_search:
    path: /ud/deportes/prestamo/search/{id}
    defaults: { _controller: "DeportesBundle:PrestamoDeportes:search"}
    options:
            expose: true

ud_activos_prestamo_cantidad:
    path: /ud/activos/prestamo/cantidad/{id}
    defaults: { _controller: "ActivosBundle:PrestamoActivo:cantidad" }
    options:
            expose: true

ud_activos_prestamo_search:
    path: /ud/activos/prestamo/search/{id}
    defaults: { _controller: "ActivosBundle:PrestamoActivo:search" }
    options:
            expose: true

ud_salones_prestamo_search:
    path: /ud/salones/prestamo/search/{id}
    defaults: { _controller: "SalonesBundle:PrestamoSalon:search" }
    options:
            expose: true
