<?php

namespace Proyecto\EnfermeriaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReporteEmergenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReporteEmergenciaRepository extends EntityRepository
{
}
