<?php

namespace Proyecto\EnfermeriaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeguridadSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeguridadSocialRepository extends EntityRepository
{
    public function findBySsocial($id){
        $em = $this->getEntityManager();

        $consulta = $em->createQuery('
            SELECT u.id, u.nombres, u.apellidos, s.eps, s.rh, s.telefonoContacto
            FROM EnfermeriaBundle:SeguridadSocial s JOIN s.users u
            WHERE s.id = :id
        ');

        $consulta->setParameter('id',$id);

        return $consulta->getResult();

    }
}
