<?php

namespace Proyecto\DeportesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ElementosDeportesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementosDeportesRepository extends EntityRepository
{
}
