<?php

namespace Proyecto\DeportesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MultaDeportesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultaDeportesRepository extends EntityRepository
{
    public function findByUsers($id)
    {

        $em = $this->getEntityManager();

        $consulta = $em->createQuery('
            SELECT m
            FROM DeportesBundle:MultaDeportes m
            WHERE m.users = :id
        ');

        $consulta->setParameter('id', $id);

        return $consulta->getResult();

    }
}