<?php

namespace Proyecto\DeportesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrestamoDeportesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestamoDeportesRepository extends EntityRepository
{
}
