<?php

namespace Proyecto\SeguridadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvitadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitadosRepository extends EntityRepository
{
}
