<?php

namespace Proyecto\SalonesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrestamoSalonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestamoSalonRepository extends EntityRepository
{
    public function findByPrestamos($fecha_inicio, $fecha_fin, $sala){
        $em = $this->getEntityManager();

        $consulta = $em->createQuery('
                    SELECT p.id, p.fechaInicio, p.fechaFin, s.nombreSala, u.nombres, u.apellidos
                    FROM SalonesBundle:PrestamoSalon p JOIN p.sala s JOIN p.users u
                    WHERE p.fechaInicio >= :fechainicio AND p.fechaFin <= :fechafin AND p.sala = :id
        ');

        $consulta->setParameter('fechainicio', $fecha_inicio);
        $consulta->setParameter('fechafin', $fecha_fin);
        $consulta->setParameter('id', $sala);

        return $consulta->getResult();
    }
}
