<?php

namespace Proyecto\SalonesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SalonesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalonesRepository extends EntityRepository
{
}
