<?php

namespace Proyecto\ActivosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ElementosActivosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementosActivosRepository extends EntityRepository
{
}
