<?php

namespace Proyecto\ActivosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StockActivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockActivoRepository extends EntityRepository
{
}
